name: coingecko-cd

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cd:
    name: coingecko-cd
    if: |
      github.event.pull_request.merged &&
      endsWith(github.event.pull_request.title, '/workflows/cd') &&
      github.event.pull_request.user.login != 'github-actions'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn build

      - name: Deploy
        run: yarn deploy
        env:
          POLYWRAP_WRAPSCAN_AUTH_HEADER_PROD: ${{secrets.POLYWRAP_WRAPSCAN_AUTH_HEADER_PROD}}

      - name: PR New URI
        uses: peter-evans/create-pull-request@v3
        with:
          branch: coingecko-cd-pr-${{github.event.number}}
          commit-message: "[CD] coingecko"
          title: "[CD] coingecko"
          body: "Triggered by: https://github.com/${{github.repository}}/pull/${{github.event.number}}"